#pragma config(Motor,  port2,           leftMotor,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Sensor, dgtl1,  ultraSensor,    sensorSONAR_cm)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	bool flag = false;
	while (!flag){
		flag = (bool)(int)vexRT[Btn6U];
	}
	while (SensorValue[ultraSensor] < 80){
		motor[port2] = 63;
		motor[port3] = 63;
	}
	motor[port2] = 0;
	motor[port3] = 0;


}
