#pragma config(Sensor, dgtl1,  ultraSensor,    sensorSONAR_cm)
#pragma config(Motor,  port2,           rightMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           tempSensor,    tmotorVex269_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	bool override = false;
	bool flag = false;
	while (!flag && !override){
		flag = (bool)(int)vexRT[Btn6U];
		override = (bool)(int)vexRT[Btn5U];
	}

	while (SensorValue[ultraSensor] < 80){
		motor[port2] = 30;
		motor[port3] = 30;
	}
	motor[port2] = 0;
	motor[port3] = 0;

	while (true){
		motor[leftMotor] = vexRT[Ch3];
		motor[rightMotor] = vexRT[Ch2];
		if (vexRT[Btn8U]){motor[tempSensor] = 30;}
		else if (vexRT[Btn8D]){motor[tempSensor] = -30;}
		else {motor[tempSensor] = 0;}
	}


}
