#pragma config(Sensor, dgtl4,  dataSpecifierLight, sensorLEDtoVCC)
#pragma config(Sensor, dgtl5,  noDataLight,    sensorLEDtoVCC)
#pragma config(Sensor, dgtl6,  l6,             sensorLEDtoVCC)
#pragma config(Sensor, dgtl7,  l5,             sensorLEDtoVCC)
#pragma config(Sensor, dgtl8,  l4,             sensorLEDtoVCC)
#pragma config(Sensor, dgtl9,  l3,             sensorLEDtoVCC)
#pragma config(Sensor, dgtl10, l2,             sensorLEDtoVCC)
#pragma config(Sensor, dgtl11, l1,             sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, l0,             sensorLEDtoVCC)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool lightDisplay[8];

void allLightsOff(){
	SensorValue(l0) = 0;
	SensorValue(l1) = 0;
	SensorValue(l2) = 0;
	SensorValue(l3) = 0;
	SensorValue(l4) = 0;
	SensorValue(l5) = 0;
	SensorValue(l6) = 0;
	SensorValue(noDataLight) = 0;
	SensorValue(dataSpecifierLight) = 0;

}
void displayNumber(){
	for(int i = 0; i < 4; i++){
		SensorValue(dataSpecifierLight) = 1;
		wait1Msec(500);
		SensorValue(dataSpecifierLight) = 0;
		wait1Msec(500);
	}
	SensorValue(l0) = (int) lightDisplay[0];
	SensorValue(l1) = (int) lightDisplay[1];
	SensorValue(l2) = (int) lightDisplay[2];
	SensorValue(l3) = (int) lightDisplay[3];
	SensorValue(l4) = (int) lightDisplay[4];
	SensorValue(l5) = (int) lightDisplay[5];
	SensorValue(l6) = (int) lightDisplay[6];
	SensorValue(noDataLight) = (int) lightDisplay[7];
	SensorValue(dataSpecifierLight) = 1;
	wait1Msec(5000);
}

void changeDisplay(int data){
	SensorValue(dataSpecifierLight) = 0;
	int temp = data;
	if (data > 127){lightDisplay[7] = true; return;}
	if (temp >= 64){
		lightDisplay[6] = true; temp -= 64;
	}else{lightDisplay[6] = false;}
	if (temp >= 32){
		lightDisplay[5] = true; temp -= 32;
	}else{lightDisplay[5] = false;}
	if (temp >= 16){
		lightDisplay[4] = true; temp -= 16;
	}else{lightDisplay[4] = false;}
	if (temp >= 8){
		lightDisplay[3] = true; temp -= 8;
	}else{lightDisplay[3] = false;}
	if (temp >= 4){
		lightDisplay[2] = true; temp -= 4;
	}else{lightDisplay[2] = false;}
	if (temp >= 2){
		lightDisplay[1] = true; temp -= 2;
	}else{lightDisplay[1] = false;}
	if (temp >= 1){
		lightDisplay[0] = true; temp -= 1;
	}else{lightDisplay[0] = false;}
}

task main()
{
	allLightsOff();
	changeDisplay(5);
	displayNumber();
	allLightsOff();


}
