#pragma config(Motor,  port2,           rightMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,    tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (1 == 1){ //Infinite loop; required for robot driving control
		//Two driving motors
		motor[leftMotor] = vexRT[Ch3];
		motor[rightMotor] = vexRT[Ch2];
	}
}
