#pragma config(Sensor, dgtl3,  enc,            sensorQuadEncoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true){
		wait1Msec(500);
		writeDebugStreamLine("%d", SensorValue[enc]);
	}



}
