#pragma config(Sensor, dgtl1,  edgeDet,        sensorSONAR_cm)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	while (true){
		writeDebugStream("%d\n", SensorValue[edgeDet]);
		wait1Msec(500);
	}
}
